language: python

python:
  - 2.7

install:
  - pip install --use-mirrors nose numpy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install --use-mirrors PIL; fi
  - python setup.py install

script:
  - mkdir ../foo
  - cd ../foo
  - python ../matplotlib/tests.py matplotlib.tests.test_axes:test_stackplot
