language: python

python:
  - 2.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev libatlas-dev
  - pip install --use-mirrors numpy
  - pip install --use-mirrors nose > /dev/null
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install --use-mirrors PIL > /dev/null; fi
  - python setup.py install

script:
  - mkdir ../foo
  - cd ../foo
  - python ../matplotlib/tests.py matplotlib.tests.test_axes:test_stackplot
